### ISSUE TITLE
Can you tell me how to use it with Jasmine?

### ISSUE THREAD

**Issue by melanke** [gardr/mock-phantom-touch-events#1]
Hi, I found your API because I really need to test touch events with Jasmine, but I am not used to work with this kind of tool. I copy-paste your code and called createTouchEvent([mycanvaselement], "touchstart", [0, 0]);

and it doesn't works.

should I use npm to get it and configure in Gruntfile.js?

I really need your help.

Thank you.

**Comment by sveisvei** [comment]
Can you provide some code in a jsbin / gist?

**Comment by melanke** [comment]
I have this project:
https://github.com/CascadeCanvas/CascadeCanvas

and this test class, for testing mouse events:
https://github.com/CascadeCanvas/CascadeCanvas/blob/master/specs/mouse.js

but I am not able to mock touch events.

I am mocking mouse events like this:
canvas.onmousedown({});

**Comment by sveisvei** [comment]
Have you tried to use the method touchActionSequence or createTouchEvent ?

---

Actual usage:
https://github.com/gardr/validator/blob/master/lib/rule/instrument/touch.js#L30

_this will only work in PhantomJS_ as its an old implementation inside phantom (pre 2.0).
https://github.com/gardr/mock-phantom-touch-events/blob/master/lib/index.js#L47

Added canvas element to test here:
https://github.com/gardr/mock-phantom-touch-events/commit/1ad40e950c42f5a5cfb37792f4f9f555bc34f25f

**Comment by melanke** [comment]
This test fails
https://gist.github.com/melanke/0160110c5dc1e7fda48d#file-mouse-js-L254

mouse:Mocks TouchStart...Mocks TouchStart: failed
  Expected false to be true. (2)

**Comment by sveisvei** [comment]
createTouchEvent returns a new function, tried to update to createTouchEvent(canvas, "touchstart", [0, 0])(); ? Are you sure this is running in PhantomJS? If not phantom, the api fro creating TouchEvents and TouchList are different.

**Comment by melanke** [comment]
Haha, thank you very much! 

``` javascript
 createTouchEvent(canvas, "touchstart", [0, 0])();
```

Worked for me!

There is any documentation or examples? 
Now I am stuck with an error trying to trigger "touchend":

``` javascript
createTouchEvent(canvas, "touchend", [0, 0])();
```

**Comment by melanke** [comment]
Yes, I am running on Node.js, with Grunt and jasmine.
Any doubts just check the repository: https://github.com/CascadeCanvas/CascadeCanvas
